setup.entity = {
    101: {
        name: "Malek Bach",
        identity: "Weak Bandit",
        race: "Human",
        gender: ["Male", "Female"],
        desc: "An entity's description",
        img: "male/1775282379030.png",
        age: [16, 40],
        str: [1, 5],
        con: [1, 6],
        int: [1, 3],
        agi: [1, 4],
        per: [1, 3],
        luck: [0.5, 1],
        skill: [101, 102],
        equipment: {
            head: 0,
            back: 0,
            chest: 0,
            leg: 0,
            feet: 0,
            rightArm: 0,
            leftArm: 0,
            leftAcc: 0,
            rightAcc: 0,
            neck: 0
        },
    },
    102: {
        name: "Barh Major",
        identity: "Strong Bandit",
        race: "Human",
        gender: ["Male", "Female"],
        desc: "An entity's description",
        img: "male/1775282379030.png",
        age: [16, 40],
        str: [1, 8],
        con: [1, 9],
        int: [1, 5],
        agi: [1, 7],
        per: [1, 5],
        luck: [0.6, 1],
        skill: [101, 102, 103]
    },
    103: {
        name: "Yao Xing",
        identity: "Village Bully",
        race: "Human",
        gender: ["Male", "Female"],
        desc: "An entity's description",
        img: "male/1775282379030.png",
        age: [13, 20],
        str: [1, 3],
        con: [1, 4],
        int: [1, 2],
        agi: [1, 2],
        per: [1, 2],
        luck: [0.45, 0.95],
        skill: [101, 102]
    },
};